#! /bin/sh
### BEGIN INIT INFO
# Provides:          </home/pi/hotspot>
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage my cool stuff
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

cd /home/pi/git/rpi_ws281x/python/light_suite/
touch teststart
echo "Starting Suite" >> teststart
sudo PYTHONPATH=".:build/lib.linux-armv7l-2.7" python suite_animations.py &&
echo "Suite Started" >> teststart

case "$1" in
  start)
    log_begin_msg "Starting my Hotspot service"
service hostapd stop
service udhcpd stop
service hostapd start
service udhcpd start
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping the Hotspot service unfortunately"

    # do something to kill the service or cleanup or nothing

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/home/pi/hotspot {start|stop}"
    exit 1
    ;;
esac
